### ISSUE TITLE
write backend for Trac

### ISSUE THREAD

**Issue by brainwane** [MetricsGrimoire/Bicho#113]
Suggestion: a new Bicho backend that grabs data from Trac bugtrackers. I started on this but stopped and won't be continuing anytime soon; feel free to [take a look at my unfinished work](https://github.com/brainwane/Bicho/blob/trac/Bicho/backends/trac.py). I suggest you use the `xmlrpclib` Python library, and use [the Django project](https://code.djangoproject.com/wiki/OpenData#trac-s-rpc-interface) as a site to test against.

**Comment by rodrigoprimo** [comment]
+1

**Comment by rodrigoprimo** [comment]
Trac support has been added by @sduenas on commit bc31d46fe0534b6f796cc19fc5e7a98d793a3d5e.
