### ISSUE TITLE
Error with Qt Codereview

### ISSUE THREAD

**Issue by athanrous** [MetricsGrimoire/Bicho#129]
I am trying to mine the Qt Codereview platform by using Bicho :
bicho -g --db-user-out=root --db-password-out=root --db-database-out=qt -b gerrit --backend-user="zoumpis" --backend-password=“mypass” -u codereview.qt-project.org --gerrit-project="qt/qtbase" -g

And I receive the following error : 
"Checking URL: ://
Not an URL: codereview.qt-project.org
DBG: [11/Jun/2014-19:00:40] Bicho object created, options and backend initialized
Running Bicho with delay of 5 seconds
DBG: [11/Jun/2014-19:00:40] Gerrit cmd: ssh -p 29418 zoumpis@codereview.qt-project.org gerrit query project:qt/qtbase limit:500 --all-approvals --comments --format=JSON
fatal: "--comments" is not a valid option
Traceback (most recent call last):
  File "/usr/local/bin/bicho", line 25, in <module>
    retval = bicho.main.main()
  File "/Library/Python/2.7/site-packages/bicho/main.py", line 56, in main
    backend.run()
  File "/Library/Python/2.7/site-packages/bicho/backends/gerrit.py", line 492, in run
    tickets = self.getReviews(limit, last_item)
  File "/Library/Python/2.7/site-packages/bicho/backends/gerrit.py", line 449, in getReviews
    tickets_raw = subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ssh', '-p 29418', 'zoumpis@codereview.qt-project.org', 'gerrit query project:qt/qtbase limit:500 --all-approvals --comments --format=JSON']' returned non-zero exit status 1"

Also while trying the SSH connection via the follwoing command : 
"ssh ilias$ ssh -p 29418 zoumpis@codereview.qt-project.org gerrit query --format=JSON status:open project:qt/qtbase --all-approvals --comments"

I receive this error : 
"fatal: "--comments" is not a valid option"

Fyi : I have created an account in the Qt Codereview and also configured my SSH properly.

**Comment by sduenas** [comment]
Bicho was discontinued in favour of [Perceval](https://github.com/chaoss/grimoirelab-perceval/). I strongly recommend you to use it.

**Comment by sduenas** [comment]
(It's good to see you around again @athanrous ;) )

**Comment by athanrous** [comment]
@sduenas Good to see you around as well.By the way I will check Perceval and if I have any question I will let you know ;)

**Comment by jgbarah** [comment]
@athanrous, have a look at the [GrimoireLab Tutorial](https://chaoss.github.io/grimoirelab-tutorial) if you want to have a glimpse of the new tooling...
