### ISSUE TITLE
Title with apostrophe is saved partially

### ISSUE THREAD

**Issue by rodrigokuroda** [MetricsGrimoire/Bicho#140]
For example, issue https://issues.apache.org/jira/browse/DERBY-109 has title *"con.prepareStatement() throws exception with 'large' expression"* and it will saved only as *" expression"* in ```issues_ext_jira``` table. The ```issues``` table has the same problem in ```summary``` column. See some titles and summary from Apache Derby project.

![capture](https://cloud.githubusercontent.com/assets/2105818/5574758/21639434-8fb0-11e4-965a-5a405d656fef.PNG)

**Comment by sduenas** [comment]
Sorry for the delay on this. Now it's fixed.
