### ISSUE TITLE
"description" column error when inserting long datasets

### ISSUE THREAD

**Issue by dicortazar** [MetricsGrimoire/Bicho#142]
It seems that with the new versions of MySQL, what previously was a simply Warning, nowadays is an error.

I would have said that this is because the description field is fixed to some varchar, but this is not true. The description field is a "text" field.
So I'm not sure where the error is...

DBG: [12/Jan/2015-07:08:34] Getting bugzilla issues from https://bugs.eclipse.org/bugs/buglist.cgi?product=CDT&order=changeddate&ctype=csv&chfieldfrom=2007-11-22%2010:58:07
Round #0 - Total issues to retrieve: 10000
DBG: [12/Jan/2015-07:08:48] Issues to retrieve from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=203895&id=205778&id=203170&id=210730&id=178058&id=117030&id=127969&id=193057&id=187776&id=180924&id=117029&id=145270&id=207139&id=208588&id=210863&id=210740&id=193464&id=211078&id=211159&id=183126&id=211586&id=209359&id=208385&id=147390&id=211862&id=197643&id=208151&id=200508&id=212194&id=191989&id=211423&id=211603&id=212282&id=211457&id=209621&id=212417&id=212123&id=212284&id=209801&id=195160&id=211639&id=210417&id=212385&id=212552&id=212593&id=212760&id=110391&id=212819&id=72334&id=210300&id=212892&id=195943&id=210392&id=156691&id=213029&id=213287&id=213239&id=77907&id=213449&id=212890&id=212864&id=118244&id=213456&id=204988&id=213994&id=214052&id=214031&id=214103&id=203781&id=214407&id=214508&id=214438&id=209614&id=159812&id=205567&id=215132&id=214541&id=204575&id=197322&id=215303&id=215310&id=215629&id=215642&id=212524&id=215822&id=215824&id=215459&id=215789&id=124113&id=215987&id=216015&id=210346&id=215967&id=215006&id=146092&id=216017&id=186612&id=216018&id=216186&id=196278&id=91296&id=216578&id=197685&id=126092&id=216092&id=210141&id=161603&id=215539&id=209770&id=216792&id=208765&id=173848&id=212998&id=217102&id=217271&id=216016&id=217402&id=217414&id=216336&id=108207&id=214146&id=217445&id=162226&id=215783&id=215112&id=216791&id=203992&id=191315&id=110222&id=216437&id=130912&id=209582&id=201983&id=187881&id=218484&id=177011&id=196055&id=218389&id=218265&id=218617&id=200673&id=215397&id=10343&id=106279&id=168924&id=100641&id=211756&id=218289&id=215065&id=218615&id=156692&id=45404&id=214590&id=127490&id=100579&id=104706&id=218954&id=219228&id=219128&id=199551&id=218895&id=219456&id=182450&id=219651&id=219616&id=219673&id=219308&id=219684&id=219840&id=219938&id=219424&id=218194&id=220166&id=219922&id=218272&id=220233&id=219003&id=220149&id=219935&id=217918&id=220358&id=219674&id=219950&id=220308&id=178976&id=159731&id=192656&id=191980&id=220572&id=219834&id=220655&id=69874&id=165655&id=192764&id=220749&id=210128&id=220097&id=220725&id=219923&id=208300&id=186603&id=196421&id=204367&id=220838&id=215906&id=209550&id=209762&id=220989&id=221029&id=221635&id=221796&id=215884&id=219446&id=79370&id=221960&id=222026&id=220736&id=222112&id=222154&id=222093&id=221853&id=216533&id=219773&id=219993&id=221858&id=222390&id=222435&id=118895&id=222474&id=222465&id=222689&id=205840&id=156788&id=133901&id=222398&id=219174&id=222721&id=222728&id=222777&id=222467&id=214447&id=215768&id=222742&id=223020&id=223059&id=223062&id=220158&id=216527&id=222226&id=194026&ctype=xml&excludefield=attachmentdata

DBG: [12/Jan/2015-07:09:02] Retrieving activity of issue #203895 from https://bugs.eclipse.org/bugs/show_activity.cgi?id=203895
Traceback (most recent call last):
  File "/usr/local/bin/bicho", line 25, in <module>
    retval = bicho.main.main()
  File "/usr/local/lib/python2.7/site-packages/bicho/main.py", line 56, in main
    backend.run()
  File "/usr/local/lib/python2.7/site-packages/bicho/backends/bg.py", line 956, in run
    self._process_issues()
  File "/usr/local/lib/python2.7/site-packages/bicho/backends/bg.py", line 1052, in _process_issues
    self._retrieve_issues(ids, url, self.tracker.id)
  File "/usr/local/lib/python2.7/site-packages/bicho/backends/bg.py", line 1117, in _retrieve_issues
    self._store_issue(issue, trk_id)
  File "/usr/local/lib/python2.7/site-packages/bicho/backends/bg.py", line 1133, in _store_issue
    self.bugsdb.insert_issue(issue, trk_id)
  File "/usr/local/lib/python2.7/site-packages/bicho/db/database.py", line 179, in insert_issue
    self.store.flush()
  File "/usr/lib64/python2.7/site-packages/storm/store.py", line 485, in flush
    self._flush_one(obj_info)
  File "/usr/lib64/python2.7/site-packages/storm/store.py", line 522, in _flush_one
    result = self._connection.execute(expr)
  File "/usr/lib64/python2.7/site-packages/storm/databases/mysql.py", line 88, in execute
    result = Connection.execute(self, statement, params)
  File "/usr/lib64/python2.7/site-packages/storm/database.py", line 238, in execute
    raw_cursor = self.raw_execute(statement, params)
  File "/usr/lib64/python2.7/site-packages/storm/database.py", line 322, in raw_execute
    self._check_disconnect(raw_cursor.execute, *args)
  File "/usr/lib64/python2.7/site-packages/storm/database.py", line 371, in _check_disconnect
    return function(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.DataError: (1406, "Data too long for column 'description' at row 1")

**Comment by dicortazar** [comment]
We may want to modify the text type to mediumtext or even longtext according to http://stackoverflow.com/questions/13932750/tinytext-text-mediumtext-and-longtext-in-mysql-maximum-storage-sizes

**Comment by dicortazar** [comment]
This error (mysql_exceptions.DataError: (1406, "Data too long for column...) also takes place with the following fields:

* flag
* keywords
* status_whiteboard
* bug_file_loc

**Comment by sduenas** [comment]
I've update the size of some columns but to avoid this problem I suggest to remove `STRICT_TRANS_TABLES` value from `sql-mode` parameter on MySQL configuration.
